name: Run RSpec Tests and Upload Coverage

on: [push, pull_request]

jobs:
  test-and-coveralls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Adjust based on your project
          bundler-cache: true
      - name: Run Tests and Generate Coverage
        run: |
          bundle exec rspec
      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/lcov.info
